rules: ({
    match = "window_type = 'normal'";
    shader = "/home/connor/.config/picom/smoke.glsl";
    
    animations = (

        {
            # --- OPENING ANIMATION ---
            triggers = ["open"];
            duration = 0.1;
            opacity-duration = 1;
            initial-scale = 0;

            anim-curve = {
                curve = "cubic-bezier(0.5, 0.5, 0.5, 0.5)";
                start = 0;
                end = 1;
                duration = "duration";
            }

            opacity-curve = {
                curve = "linear"; # Linear is usually best for shader-driven anims
                start = 0.4;
                end = 1;
                duration = "opacity-duration";
            }
            scale-x = "anim-curve * (1 - initial-scale) + initial-scale";
            scale-y = "anim-curve * (1 - initial-scale) + initial-scale";
            offset-x = "(1 - scale-x) / 2 * window-width";
            offset-y = "(1 - scale-y) / 2 * window-height";
            opacity = "opacity-curve";
        },

        {
            # --- CLOSING ANIMATION ---
            triggers = ["close"];
            duration = 1.0;         # Usually faster for closing
            opacity-duration = 1.0;
            
            # Use a simple curve for closing to avoid the 'bounce' 
            # from your bezier(0, 1.5, 1, 1) during exit
            exit-curve = {
                curve = "cubic-bezier(0.5, 0.5, 0.5, 0.5)";
                start = 1;
                end = 0.9;
                duration = "duration";
            }
            opacity-curve = {
                curve = "linear";
                start = 1; # Starts at full opacity
                end = 0;   # Ends at zero, triggering the reverse shader
                duration = "opacity-duration";
            }
            
            opacity = "opacity-curve";


            # If you want it to shrink while closing:
            scale-x = "exit-curve";
            scale-y = "exit-curve";
            offset-x = "(1 - scale-x) / 2 * window-width";
            offset-y = "(1 - scale-y) / 2 * window-height";
        }

    )
})


shadow = false;

frame-opacity = 1.0;
corner-radius = 0


# glx requires gpu/integrated gpu, if you're in a virtual machine maybe xrender or just no picom at all
backend = "glx"

vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = true
unredir-if-possible = true
detect-transient = true;
use-damage = true;
